import { StyleSheet } from 'react-native';

export const colors = {
  background: '#F5F4EF', surface: '#FFFFFF', ink: '#182D28',
  muted: '#718078', green: '#143F36', mint: '#CDEAAB',
  border: '#E5E8E0', pale: '#EDF2E8', amber: '#996114',
  amberBg: '#FFF1D7', red: '#AB4D42', redBg: '#FCECE7',
};

// External styles: dipisahkan dari file layar lalu diimpor oleh komponen.
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  appFrame: { flex: 1, width: '100%', maxWidth: 520, alignSelf: 'center' },
  safe: { flex: 1, backgroundColor: colors.background },
  content: { padding: 22, paddingBottom: 28, gap: 20 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  grow: { flex: 1 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 3 },
  logo: { width: 43, height: 43, backgroundColor: colors.green, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  brand: { color: colors.ink, fontSize: 21, fontWeight: '800', letterSpacing: -0.7 },
  eyebrow: { color: colors.muted, fontSize: 10, fontWeight: '700', letterSpacing: 2 },
  title: { color: colors.ink, fontSize: 31, fontWeight: '800', letterSpacing: -1, lineHeight: 38 },
  subtitle: { color: colors.muted, fontSize: 13, lineHeight: 20 },
  sectionTitle: { fontSize: 19, fontWeight: '800', color: colors.ink, letterSpacing: -0.4 },
  dateChip: { backgroundColor: colors.pale, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 20 },
  dateText: { color: colors.green, fontSize: 11, fontWeight: '600' },
  stats: { flexDirection: 'row', gap: 10 },
  stat: { flex: 1, backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 17, padding: 13, gap: 8 },
  statNumber: { color: colors.ink, fontSize: 25, fontWeight: '800', letterSpacing: -0.5 },
  statLabel: { color: colors.muted, fontSize: 11, fontWeight: '500' },
  hero: { backgroundColor: colors.green, borderRadius: 24, padding: 23, gap: 17, overflow: 'hidden' },
  heroEyebrow: { color: '#B9D4C8', fontSize: 10, fontWeight: '700', letterSpacing: 1.9 },
  heroTicket: { color: colors.mint, fontSize: 54, fontWeight: '800', letterSpacing: -2, lineHeight: 64 },
  heroName: { color: 'white', fontSize: 21, fontWeight: '700', marginTop: 3 },
  heroMeta: { color: '#BCD1C7', fontSize: 12, lineHeight: 19 },
  heroIcon: { width: 58, height: 58, borderRadius: 18, backgroundColor: '#2A5145', justifyContent: 'center', alignItems: 'center' },
  heroBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#2A5145', paddingVertical: 6, paddingHorizontal: 10, borderRadius: 20 },
  heroBadgeText: { color: colors.mint, fontSize: 10, fontWeight: '600' },
  dot: { height: 5, width: 5, borderRadius: 3, backgroundColor: colors.mint },
  button: { minHeight: 50, borderRadius: 14, paddingHorizontal: 18, paddingVertical: 13, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, backgroundColor: colors.green },
  buttonText: { fontSize: 14, fontWeight: '700', color: 'white' },
  buttonLight: { backgroundColor: colors.mint },
  buttonLightText: { color: colors.green },
  buttonOutline: { backgroundColor: 'transparent', borderWidth: 1, borderColor: colors.border },
  buttonOutlineText: { color: colors.ink },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.75 },
  badge: { backgroundColor: colors.pale, borderRadius: 16, paddingHorizontal: 9, paddingVertical: 4 },
  badgeText: { fontSize: 10, fontWeight: '600', color: colors.green },
  search: { flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 13, paddingHorizontal: 13, minHeight: 45 },
  searchInput: { flex: 1, fontSize: 13, color: colors.ink, paddingVertical: 11, minWidth: 0 },
  filters: { flexDirection: 'row', backgroundColor: '#E8ECE3', padding: 4, borderRadius: 13, gap: 3 },
  filter: { flex: 1, minHeight: 37, paddingHorizontal: 8, justifyContent: 'center', alignItems: 'center', borderRadius: 10 },
  filterActive: { backgroundColor: colors.surface },
  filterText: { fontSize: 12, color: colors.muted, fontWeight: '600' },
  filterTextActive: { color: colors.green },
  queueList: { gap: 10 },
  customer: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 17, padding: 15, gap: 11 },
  ticketBox: { minWidth: 54, height: 52, borderRadius: 12, backgroundColor: colors.pale, justifyContent: 'center', alignItems: 'center' },
  ticketSmall: { color: colors.green, fontSize: 14, fontWeight: '800' },
  customerName: { color: colors.ink, fontSize: 15, fontWeight: '700' },
  customerMeta: { color: colors.muted, fontSize: 11, marginTop: 4, lineHeight: 16 },
  cardFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 10, borderTopWidth: 1, borderTopColor: colors.border },
  smallText: { color: colors.muted, fontSize: 11, lineHeight: 17 },
  cancelButton: { minHeight: 36, justifyContent: 'center', paddingHorizontal: 3 },
  cancelText: { color: colors.red, fontSize: 11, fontWeight: '600' },
  empty: { alignItems: 'center', paddingHorizontal: 22, paddingVertical: 32, gap: 10, borderRadius: 18, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  emptyTitle: { color: colors.ink, fontSize: 16, fontWeight: '700', textAlign: 'center' },
  emptyText: { fontSize: 12, color: colors.muted, lineHeight: 19, textAlign: 'center' },
  note: { backgroundColor: colors.pale, borderRadius: 14, padding: 14, gap: 8 },
  noteText: { color: '#5B7165', fontSize: 11, lineHeight: 18, flex: 1 },
  storageNote: { alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 5 },
  bottomAction: { backgroundColor: colors.background, paddingHorizontal: 22, paddingTop: 10, paddingBottom: 13, borderTopWidth: 1, borderColor: colors.border },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(12,29,22,0.48)', justifyContent: 'center', padding: 20 },
  modalCard: { width: '100%', maxWidth: 460, alignSelf: 'center', borderRadius: 24, backgroundColor: colors.background, padding: 24, gap: 20, maxHeight: '92%' },
  modalTitle: { color: colors.ink, fontSize: 23, fontWeight: '800', letterSpacing: -0.5 },
  close: { minHeight: 44, minWidth: 44, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.pale, borderRadius: 13 },
  label: { color: colors.ink, fontSize: 12, fontWeight: '700', marginBottom: 8 },
  input: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 13, minHeight: 51, paddingHorizontal: 14, fontSize: 15, color: colors.ink },
  inputError: { borderColor: colors.red },
  errorText: { color: colors.red, fontSize: 12, marginTop: 7 },
  serviceOption: { padding: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 15, backgroundColor: colors.surface, flexDirection: 'row', alignItems: 'center', gap: 12 },
  serviceSelected: { borderColor: colors.green, backgroundColor: colors.pale },
  radio: { height: 19, width: 19, borderRadius: 10, borderWidth: 1.5, borderColor: colors.muted, alignItems: 'center', justifyContent: 'center' },
  radioDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: colors.green },
  amount: { color: colors.ink, fontSize: 13, fontWeight: '700' },
  formNote: { padding: 12, backgroundColor: colors.pale, borderRadius: 13, flexDirection: 'row', gap: 8, alignItems: 'center' },
  toast: { marginHorizontal: 22, marginBottom: 8, padding: 13, borderRadius: 13, backgroundColor: colors.pale, borderWidth: 1, borderColor: '#D3DEC9' },
  toastText: { color: colors.green, fontSize: 12, lineHeight: 18 },
  serviceCard: { backgroundColor: colors.surface, borderRadius: 19, borderWidth: 1, borderColor: colors.border, padding: 19, gap: 15 },
  serviceIcon: { width: 47, height: 47, borderRadius: 14, backgroundColor: colors.pale, justifyContent: 'center', alignItems: 'center' },
});
